using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace loader
{
    public class ResIncome
    {
        public string AccessibilityFeatures { get; set; }
        public Nullable<double> Acres { get; set; }
        public string AdNumber { get; set; }
        public string APN { get; set; }
        public string Appliances { get; set; }
        public Nullable<double> AppliancesYN { get; set; }
        public Nullable<double> Area { get; set; }
        public string Assessments { get; set; }
        public Nullable<double> AssessmentsYN { get; set; }
        public string Association { get; set; }
        public string AssociationDues1 { get; set; }
        public string AssociationDues1Frequency { get; set; }
        public string AssociationDues2 { get; set; }
        public string AssociationDues2Frequency { get; set; }
        public string AssociationName1 { get; set; }
        public Nullable<double> AssociationYN { get; set; }
        public string AttachedStructure { get; set; }
        public string BuildersName { get; set; }
        public string BuildersTractCode { get; set; }
        public string BuildersTractName { get; set; }
        public Nullable<double> Caprate { get; set; }
        public Nullable<double> CDOM { get; set; }
        public string CDOMResetYN { get; set; }
        public string City { get; set; }
        public string COLA_Board { get; set; }
        public string COLA_FirstName { get; set; }
        public string COLA_LastName { get; set; }
        public string COLA_PublicID { get; set; }
        public Nullable<double> COLA_StateLicenseNumber { get; set; }
        public Nullable<double> COLO_Code { get; set; }
        public string COLO_Name { get; set; }
        public string CommonWalls { get; set; }
        public string CommunityFeatures { get; set; }
        public Nullable<double> ContactOrder1 { get; set; }
        public Nullable<double> ContactOrder2 { get; set; }
        public Nullable<double> ContactOrder3 { get; set; }
        public Nullable<double> ContactOrder4 { get; set; }
        public Nullable<double> ContactOrder5 { get; set; }
        public Nullable<double> ContactOrder6 { get; set; }
        public string Cooling { get; set; }
        public Nullable<double> CoolingYN { get; set; }
        public string COSA_FirstName { get; set; }
        public string COSA_LastName { get; set; }
        public string COSA_PublicID { get; set; }
        public string COSA_StateLicenseNumber { get; set; }
        public string COSO_Code { get; set; }
        public string COSO_Name { get; set; }
        public string Country { get; set; }
        public string County { get; set; }
        public string CrossStreets { get; set; }
        public Nullable<System.DateTime> DateClosedSale { get; set; }
        public Nullable<System.DateTime> DateCmaStatus { get; set; }
        public Nullable<System.DateTime> DateListingContract { get; set; }
        public Nullable<double> DeletedYN { get; set; }
        public string DirectionFaces { get; set; }
        public string Disclosures { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<double> DOM { get; set; }
        public string DoorFeatures { get; set; }
        public string Elevation { get; set; }
        public string EntryLevel { get; set; }
        public string EntryLocation { get; set; }
        public string ExteriorFeatures { get; set; }
        public string FenceYN { get; set; }
        public string Fencing { get; set; }
        public string Fireplace { get; set; }
        public Nullable<double> FireplaceYN { get; set; }
        public string Floor { get; set; }
        public string Foundation { get; set; }
        public string GreenBuildingCertification { get; set; }
        public string GreenCertificationRating { get; set; }
        public string GreenCertifyingBody { get; set; }
        public string GreenEnergyEfficient { get; set; }
        public string GreenEnergyGeneration { get; set; }
        public string GreenIndoorAirQuality { get; set; }
        public string GreenLocation { get; set; }
        public string GreenSustainability { get; set; }
        public string GreenWalkScore { get; set; }
        public string GreenWaterConservation { get; set; }
        public string GreenYearCertified { get; set; }
        public Nullable<double> GrossMultiplier { get; set; }
        public Nullable<double> GrossOperatingIncome { get; set; }
        public Nullable<double> GrossScheduledIncome { get; set; }
        public string Heating { get; set; }
        public Nullable<double> HeatingYN { get; set; }
        public string InteriorFeatures { get; set; }
        public Nullable<double> InternetSendAddressYN { get; set; }
        public Nullable<double> InternetSendListingYN { get; set; }
        public string LA_Board { get; set; }
        public string LA_FirstName { get; set; }
        public string LA_LastName { get; set; }
        public string LA_Publicid { get; set; }
        public Nullable<double> LA_StateLicenseNumber { get; set; }
        public string LandFeeLease { get; set; }
        public string LastChangeType { get; set; }
        public string Laundry { get; set; }
        public Nullable<double> LaundryYN { get; set; }
        public string ListingKey { get; set; }
        public Nullable<double> ListPrice { get; set; }
        public string ListPriceExcludes { get; set; }
        public string ListPriceIncludes { get; set; }
        public string ListPriceLow { get; set; }
        public string LO_Code { get; set; }
        public string LO_Name { get; set; }
        public string LotDimensions { get; set; }
        public string LotFeatures { get; set; }
        public Nullable<double> LotSquareFootage { get; set; }
        public string MLnumber { get; set; }
        public string MLSID { get; set; }
        public string ModelName { get; set; }
        public Nullable<double> MonthlyGrossIncome { get; set; }
        public Nullable<double> NetOperatingIncome { get; set; }
        public Nullable<double> NumberElectricMeters { get; set; }
        public Nullable<double> NumberGarageSpaces { get; set; }
        public Nullable<double> NumberGasMeters { get; set; }
        public string NumberUncoveredSpaces { get; set; }
        public Nullable<double> NumberUnits { get; set; }
        public Nullable<double> NumberWaterMeters { get; set; }
        public Nullable<double> OperatingExpense { get; set; }
        public string OtherStructures { get; set; }
        public string Parking { get; set; }
        public Nullable<double> ParkingSpacesTotal { get; set; }
        public Nullable<double> ParkingYN { get; set; }
        public Nullable<double> Piccount { get; set; }
        public string Pool { get; set; }
        public Nullable<double> PoolYN { get; set; }
        public string PostalCode { get; set; }
        public string PostalCodePlus4 { get; set; }
        public Nullable<double> PreviousPrice { get; set; }
        public string PreviousStatus { get; set; }
        public Nullable<double> PricePerSqft { get; set; }
        public Nullable<double> PricePerUnit { get; set; }
        public string PropertyDescription { get; set; }
        public string Roofing { get; set; }
        public string Rooms { get; set; }
        public string SA_FirstName { get; set; }
        public string SA_LastName { get; set; }
        public string SA_PublicID { get; set; }
        public Nullable<double> SA_StateLicenseNumber { get; set; }
        public string SaleType { get; set; }
        public string SecurityExpense { get; set; }
        public string SecurityFeatures { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<double> SeniorYN { get; set; }
        public string Sewer { get; set; }
        public string SO_Code { get; set; }
        public string SO_Name { get; set; }
        public Nullable<double> SourceKey { get; set; }
        public string SourceTimestampModified { get; set; }
        public string Spa { get; set; }
        public Nullable<double> SpaYN { get; set; }
        public string SqFtSourceLot { get; set; }
        public Nullable<double> SquareFootageBuilding { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public string Stories { get; set; }
        public string StoriesTotal { get; set; }
        public string StreetDirection { get; set; }
        public string StreetDirectionSuffix { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public string StreetNumberModifier { get; set; }
        public string StreetSuffix { get; set; }
        public string StreetSuffixModifier { get; set; }
        public string StructuralCondition { get; set; }
        public string Style { get; set; }
        public string ThomasGuide { get; set; }
        public Nullable<System.DateTime> TimestampModified { get; set; }
        public Nullable<System.DateTime> TimestampOffMarket { get; set; }
        public Nullable<System.DateTime> TimestampPhotoModified { get; set; }
        public Nullable<System.DateTime> TimestampStatusChange { get; set; }
        public Nullable<double> TotalExpenses { get; set; }
        public string TractName { get; set; }
        public Nullable<double> TractNumber { get; set; }
        public string TractSubAreaCode { get; set; }
        public Nullable<double> Type10ActualRent { get; set; }
        public Nullable<double> Type10Baths { get; set; }
        public string Type10Bedrooms { get; set; }
        public string Type10Furnished { get; set; }
        public string Type10GarageAttached { get; set; }
        public string Type10GarageSpaces { get; set; }
        public Nullable<double> Type10ProFormaRent { get; set; }
        public Nullable<double> Type10TotalRent { get; set; }
        public Nullable<double> Type10Units { get; set; }
        public Nullable<double> Type11ActualRent { get; set; }
        public Nullable<double> Type11Baths { get; set; }
        public string Type11Bedrooms { get; set; }
        public string Type11Furnished { get; set; }
        public string Type11GarageAttached { get; set; }
        public string Type11GarageSpaces { get; set; }
        public Nullable<double> Type11ProFormaRent { get; set; }
        public Nullable<double> Type11TotalRent { get; set; }
        public Nullable<double> Type11Units { get; set; }
        public Nullable<double> Type12ActualRent { get; set; }
        public Nullable<double> Type12Baths { get; set; }
        public string Type12Bedrooms { get; set; }
        public string Type12Furnished { get; set; }
        public string Type12GarageAttached { get; set; }
        public string Type12GarageSpaces { get; set; }
        public Nullable<double> Type12ProFormaRent { get; set; }
        public Nullable<double> Type12TotalRent { get; set; }
        public Nullable<double> Type12Units { get; set; }
        public Nullable<double> Type13ActualRent { get; set; }
        public Nullable<double> Type13Baths { get; set; }
        public string Type13Bedrooms { get; set; }
        public string Type13Furnished { get; set; }
        public string Type13GarageAttached { get; set; }
        public string Type13GarageSpaces { get; set; }
        public Nullable<double> Type13ProFormaRent { get; set; }
        public Nullable<double> Type13TotalRent { get; set; }
        public Nullable<double> Type13Units { get; set; }
        public Nullable<double> Type1ActualRent { get; set; }
        public Nullable<double> Type1Baths { get; set; }
        public Nullable<double> Type1Bedrooms { get; set; }
        public string Type1Furnished { get; set; }
        public string Type1GarageAttached { get; set; }
        public Nullable<double> Type1GarageSpaces { get; set; }
        public Nullable<double> Type1ProFormaRent { get; set; }
        public Nullable<double> Type1TotalRent { get; set; }
        public Nullable<double> Type1Units { get; set; }
        public Nullable<double> Type2ActualRent { get; set; }
        public Nullable<double> Type2Baths { get; set; }
        public Nullable<double> Type2Bedrooms { get; set; }
        public string Type2Furnished { get; set; }
        public string Type2GarageAttached { get; set; }
        public Nullable<double> Type2GarageSpaces { get; set; }
        public Nullable<double> Type2ProFormaRent { get; set; }
        public Nullable<double> Type2TotalRent { get; set; }
        public Nullable<double> Type2Units { get; set; }
        public Nullable<double> Type3ActualRent { get; set; }
        public Nullable<double> Type3Baths { get; set; }
        public Nullable<double> Type3Bedrooms { get; set; }
        public string Type3Furnished { get; set; }
        public string Type3GarageAttached { get; set; }
        public string Type3GarageSpaces { get; set; }
        public Nullable<double> Type3ProFormaRent { get; set; }
        public Nullable<double> Type3TotalRent { get; set; }
        public Nullable<double> Type3Units { get; set; }
        public Nullable<double> Type4ActualRent { get; set; }
        public Nullable<double> Type4Baths { get; set; }
        public Nullable<double> Type4Bedrooms { get; set; }
        public string Type4Furnished { get; set; }
        public string Type4GarageAttached { get; set; }
        public string Type4GarageSpaces { get; set; }
        public Nullable<double> Type4ProFormaRent { get; set; }
        public Nullable<double> Type4TotalRent { get; set; }
        public Nullable<double> Type4Units { get; set; }
        public Nullable<double> Type5ActualRent { get; set; }
        public Nullable<double> Type5Baths { get; set; }
        public Nullable<double> Type5Bedrooms { get; set; }
        public string Type5Furnished { get; set; }
        public string Type5GarageAttached { get; set; }
        public string Type5GarageSpaces { get; set; }
        public Nullable<double> Type5ProFormaRent { get; set; }
        public Nullable<double> Type5TotalRent { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}