//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmlservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public string UserID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string ID { get; set; }
        public string Data { get; set; }
        public System.DateTime Created { get; set; }
    }
}
