//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmlservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoriate
    {
        public int FavoriateID { get; set; }
        public string UserID { get; set; }
        public string MLNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
