//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmlservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExpense
    {
        public Nullable<double> ListingKey { get; set; }
        public Nullable<double> ListPrice { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public Nullable<double> GrossIncome { get; set; }
        public Nullable<double> Mortage { get; set; }
        public Nullable<double> PropertyTax { get; set; }
        public Nullable<double> PropertyManagement { get; set; }
        public decimal Insurance { get; set; }
    }
}
