//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kmlservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwResIncomeSummary
    {
        public string MLnumber { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public string City { get; set; }
        public string PropertyDescription { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinate { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> LotSquareFootage { get; set; }
        public Nullable<double> ListingKey { get; set; }
        public string MediaURL { get; set; }
    }
}
